name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        env:
          SDL_VIDEODRIVER: "dummy" 
          SDL_AUDIODRIVER: "disk"
        run: poetry run invoke coverage
      - name: Coverage report
        run: poetry run coverage xml
      - name: Coverage report to Codecov
        uses: codecov/codecov-action@v2
